Repository FalkorDB/FalkorDB, pull requests merged in 2024-02, with the labels that each got.

#557 Optimize build and release pipelines
  .github/workflows/build.yml
  .github/workflows/release-image.yml
  build/docker/Dockerfile
  build/docker/Dockerfile.compiler
  tests/Dockerfile
  tests/fuzz/process.py
  tests/fuzz/requirements.txt
  tests/requirements.txt
Labels: size:L, lgtm

#559 Add browser to docker image
  build/docker/Dockerfile
  build/docker/run.sh
Labels: size:S, lgtm

#564 Add browser to docker image
  .github/workflows/build.yml
Labels: size:XS

#566 add dependabot
  .github/dependabot.yml
Labels: size:XS, lgtm

#572 resolve compilation warnings
  deps/libcypher-parser/lib/src/ast_foreach.c
  deps/libcypher-parser/lib/src/ast_query.c
  deps/libcypher-parser/lib/src/ast_statement.c
  deps/libcypher-parser/lib/src/cypher-parser.h.in
Labels: size:S

#574 update redis san version
  tests/flow/tests.sh
Labels: size:XS

#565 Add browser to docker image
  .github/workflows/build.yml
  .github/workflows/release-image.yml
Labels: size:M, lgtm

#577 Add browser to docker image
  .github/workflows/release-image.yml
Labels: size:M

#578 fix release
  .github/workflows/release-image.yml
Labels: size:S

#579 fix docker image
  build/docker/run.sh
Labels: size:XS

#580 fix timeout config check
  src/commands/cmd_dispatcher.c
Labels: size:XS

#583 fix release commit sha
  .github/workflows/release-image.yml
Labels: size:XS, lgtm

#575 remove runtime tests, remove extra prints
  .github/workflows/sanitize.yml
  build/docker/Dockerfile.compiler
  demo/__init__.py
  demo/imdb/imdb_queries.py
  demo/social/social_queries.py
  tests/Dockerfile
  tests/flow/base.py
  tests/flow/test_access_del_entity.py
  tests/flow/test_bound_variables.py
  tests/flow/test_cache.py
  tests/flow/test_call_subquery.py
  tests/flow/test_comprehension_functions.py
  tests/flow/test_concurrent_query.py
  tests/flow/test_config.py
  tests/flow/test_constraint.py
  tests/flow/test_edge_index_scans.py
  tests/flow/test_encode_decode.py
  tests/flow/test_foreach.py
  tests/flow/test_function_calls.py
  tests/flow/test_graph_deletion.py
  tests/flow/test_graph_info.py
  tests/flow/test_graph_merge.py
  tests/flow/test_imdb.py
  tests/flow/test_index_create.py
  tests/flow/test_index_delete.py
  tests/flow/test_index_scans.py
  tests/flow/test_list.py
  tests/flow/test_optimizations_plan.py
  tests/flow/test_optional_match.py
  tests/flow/test_order_by.py
  tests/flow/test_pagerank.py
  tests/flow/test_params.py
  tests/flow/test_path.py
  tests/flow/test_path_filter.py
  tests/flow/test_pending_queries_limit.py
  tests/flow/test_point.py
  tests/flow/test_prev_rdb_decode.py
  tests/flow/test_query_mem_limit.py
  tests/flow/test_rdb_load.py
  tests/flow/test_replication_states.py
  tests/flow/test_slowlog.py
  tests/flow/test_social.py
  tests/flow/test_star_projections.py
  tests/flow/test_stress.py
  tests/flow/test_timeout.py
  tests/flow/test_undo_log.py
  tests/flow/test_variable_length_traversals.py
  tests/flow/tests.sh
  tests/requirements.txt
Labels: size:XXL

#587 update deps
  .github/workflows/sanitize.yml
Labels: size:XS, lgtm
