Repository FalkorDB/FalkorDB, pull requests merged in 2025-02, with the labels that each got.

#933 pick the best starting point between source and dest labels
  src/arithmetic/algebraic_expression.h
  src/arithmetic/algebraic_expression/algebraic_expression.c
  src/arithmetic/algebraic_expression/algebraic_expression_mul.c
  src/arithmetic/algebraic_expression/algebraic_expression_operand.c
  src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
  src/arithmetic/algebraic_expression/utils.c
  src/configuration/config.c
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan_build/build_match_op_tree.c
  src/execution_plan/execution_plan_build/execution_plan_construct.c
  src/execution_plan/execution_plan_build/execution_plan_construct.h
  src/execution_plan/execution_plan_build/execution_plan_modify.c
  src/execution_plan/execution_plan_build/execution_plan_util.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/shared/scan_functions.c
  src/execution_plan/ops/shared/scan_functions.h
  src/execution_plan/optimizations/cost_base_label_scan.c
  src/execution_plan/optimizations/traverse_order.c
  src/execution_plan/optimizations/traverse_order_utils.c
  src/graph/entities/qg_node.h
  src/graph/graph.h
  src/graph/graph_statistics.c
  src/graph/query_graph.c
  src/graph/query_graph.h
  tests/flow/test_opening_node.py
Labels: x:perf, Review effort [1-5]: 4

#939 add libcurl and libcsv cache
  .github/workflows/build.yml
Labels: Review effort [1-5]: 2

#940 subquery should not be eager when performing aggregations
  src/execution_plan/execution_plan_build/build_call_subquery.c
  src/execution_plan/execution_plan_build/execution_plan_util.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_call_subquery.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_limit.c
  tests/flow/test_call_subquery.py
Labels: bug

#937 implement db.idx.fulltext.queryRelationships - full search text on re…
  src/procedures/proc_fulltext_query.h
  src/procedures/proc_fulltext_query_edge.c
  src/procedures/proc_fulltext_query_node.c
  src/procedures/procedure.c
  tests/flow/test_fulltext_query.py
  tests/flow/test_procedures.py
Labels: Review effort [1-5]: 4

#934 Add playwright tests to browser-tests job
  .github/workflows/build.yml
Labels: Review effort [1-5]: 2

#961 avoid value cloning when performing aggregations
  src/arithmetic/aggregate_funcs/agg_collect.c
  src/arithmetic/arithmetic_expression.c
  src/datatypes/array.c
  src/datatypes/array.h
  tests/flow/test_aggregation.py
Labels: x:perf

#964 string join on an empty list
  src/arithmetic/string_funcs/string_funcs.c
  tests/flow/test_function_calls.py
Labels: bug
