Repository FalkorDB/FalkorDB, pull requests merged in 2025-03, with the labels that each got.

#993 update algebraic expression on conditional traverse reset
  src/arithmetic/algebraic_expression.h
  src/arithmetic/algebraic_expression/algebraic_expression.c
  src/arithmetic/algebraic_expression/utils.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_expand_into.h
  src/execution_plan/ops/op_node_by_label_scan.c
  tests/flow/test_graph_merge.py
Labels: bug

#983 Reuse strings
  src/ast/ast.c
  src/ast/ast.h
  src/ast/ast_build_value.c
  src/ast/ast_build_value.h
  src/ast/ast_validations.c
  src/commands/execution_ctx.c
  src/configuration/config.c
  src/configuration/config.h
  src/configuration/reconf_handler.c
  src/datatypes/array.c
  src/datatypes/map.c
  src/datatypes/map.h
  src/execution_plan/execution_plan_build/execution_plan_construct.c
  src/globals.c
  src/globals.h
  src/graph/graphcontext.c
  src/query_ctx.c
  src/query_ctx.h
  src/string_pool/string_pool.c
  src/string_pool/string_pool.h
  src/util/thpool/pools.c
  src/value.c
  tests/flow/common.py
  tests/flow/test_config.py
  tests/flow/test_graph_copy.py
  tests/flow/test_load_csv.py
  tests/flow/test_persistency.py
  tests/flow/test_procedures.py
  tests/flow/test_replication.py
  tests/flow/test_replication_states.py
  tests/flow/test_ro_query.py
  tests/flow/test_string_pool.py
  tests/flow/test_timeout.py
Labels: enhancement, action:run-benchmark

#1022 Potential fix for code scanning alert no. 2: Comparison of narrow type with wide type in loop condition
  src/resultset/formatters/resultset_replybolt.c
Labels: Review effort 1/5

#1028 check rather or not to migrate a filter
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan_build/execution_plan_util.c
  src/execution_plan/ops/op.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_all_node_scan.c
  src/execution_plan/ops/op_project.c
  src/execution_plan/optimizations/optimize_cartesian_product.c
  src/filter_tree/filter_tree.c
  src/filter_tree/filter_tree.h
  tests/flow/test_path_filter.py
  tests/unit/test_execution_plan_awareness.c
Labels: bug
